app/admin/routes.py
import logging

from flask import (Blueprint, render_template, redirect, 
                   url_for, flash, current_app, request)
from flask_login import login_required, current_user
from sqlalchemy import exc

from app import db
from ..auth import admin_required, permission_required
from ..auth.models import User, Role, Permission
from ..blogs.models import Posts, Comments, CommentReply, Tag
from ..main.models import Quotes, Feedback

from .forms import EditProfileAdminForm

admin_blueprint = Blueprint('admin', __name__, 
                            static_folder="admin", 
                            static_url_path="../static/admin/",
                            url_prefix="/admin")

@admin_blueprint.route("/")
@login_required
@permission_required(Permission.ADMINISTER)
def dashboard():
    user = User.query.get(current_user.id)
    form = EditProfileAdminForm(user=user)
    posts = Posts.query.order_by(Posts.date_created.desc())
    page = request.args.get('next')
    pagination = db.paginate(posts, page=page, per_page=10, error_out=False)
    return render_template("admin/dashboard.html", user=user, form=form)

@admin_blueprint.route("/boards")
@login_required
@admin_required
def boards():
    return render_template("admin/boards.html")

@admin_blueprint.route('/comments')
@login_required
@admin_required
def comments():
    comments = Comments.query.order_by(Comments.date.desc())
    page = request.args.get('page', type=int)
    pagination = db.paginate(comments, page=page, per_page=5, error_out=False)
    return render_template("admin/models/comments.html", comments=pagination.items,
                           pagination=pagination)

@admin_blueprint.route("/comment/enable/<int:id>")
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comments.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))

@admin_blueprint.route("/comment/disable/<int:id>")
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comments.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    db.session.commit()
    
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))

@admin_blueprint.route("/comment/delete/<int:id>")
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_delete(id):
    comment = Comments.query.get_or_404(id)
    db.session.delete(comment)
    db.session.commit()
    flash("Comment deleted successfully!.", category='info')
    
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))

@admin_blueprint.route("/@<string:username>/profile/", methods=['GET', 'POST'])
@login_required
@admin_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.bio = form.about_me.data
        try:
            db.session.add(user)
            db.session.commit()
            flash("User profile changed.", category="info")
            if user.is_administrator():
                return redirect(url_for(".profile", username=user.username))
            else:
                return redirect(url_for('users.user', username=user.username))
        except exc.IntegrityError as e:
            flash("User profile not changed", category="warning")
            logging.error("User profile could not changed: {}".format(e))
    form.email.data = user.email
    form.name.data = user.display_name
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.location.data = user.location
    form.about_me.data = user.bio
    
    return render_template("admin/profile.html", form=form, user=user)

@admin_blueprint.route('/reports')
def reports():
    return "Hello"

@admin_blueprint.route("/tests/")
def tests():
    return "Hello"

@admin_blueprint.route("/users")
def users():
    bytens = User.query.order_by(User.last_seen.desc())
    page = request.args.get('page', type=int)
    pagination = db.paginate(bytens, page=page, per_page=5, error_out=False)
    return render_template("admin/models/users.html", users=pagination.items, pagination=pagination)

@admin_blueprint.route("/update/<int:user_id>/", methods=['GET', 'POST'])
@login_required
@admin_required
def update_user(user_id):
    user = User.query.filter_by(user_id).first_or_404()
    return render_template("admin/users/edit.html", user=user)

@admin_blueprint.route("/restrict/<int:user_id>/", methods=['GET', 'PUT'])
@login_required
@admin_required
def user_profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    return render_template("admin/users/user.html")

@admin_blueprint.route("/remove/<int:user_id>/", methods=['GET', 'DELETE'])
@login_required
@admin_required
def remove_user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    try:
        db.session.delete(user)
        db.session.commit()
        flash(f"User with the username {user.username} removed.", category="info")
        return redirect(url_for('.users', page=1))
    except Exception as e:
        db.session.rollback()
        flash("User not removed!.", category="warning")
        raise e
     
@admin_blueprint.route("/quotes")
def quotes():
    qts = Quotes.query.order_by(Quotes.sent.desc())
    page = request.args.get('page', type=int)
    quts = db.paginate(qts, page=page, per_page=7, error_out=False)
    return render_template("admin/models/quotes.html", quotes=quts.items, pagin=quts)

@admin_blueprint.route("/feedback")
def feed():
    backfeed = Feedback.query.order_by(Feedback.created_at.desc())
    page = request.args.get('page', type=int)
    pagination = db.paginate(backfeed, page=page, per_page=5, error_out=False)
    return render_template("admin/models/feedback.html", feedback=pagination.items, pagin=pagination)

app/main/routes.py
import random

from flask import Blueprint, render_template, redirect, request, flash, abort, url_for, session
from flask_login import login_required

from app import db
from .forms import FeedbackForm, quoteForm
from .models import Feedback, Quotes
from ..auth.models import User, Permission


main_blueprint = Blueprint("mainapp", __name__,
                           static_folder='static/mainapp', template_folder='templates/mainapp',
                           url_prefix="/RiriNjaramba")

@main_blueprint.route('/', methods=['GET', 'POST'])
def index():
    form = FeedbackForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        feed = form.feed.data
        
        details = Feedback(email=email, feed=feed)
        try:
            db.session.add(details)
            db.session.commit()
            flash("Thank you for contacting me, will be in touch shortly.", category="info")
        except Exception as e:
            db.session.rollback()
            flash(f"Something didn't go right, kindly try again: {e}", category="warning")
    return render_template('/mainapp/index.html', form=form, permission=Permission)

@main_blueprint.route('/get-quote/', methods=['GET', 'POST'])
def quote():
    service = session.get('title', '')
    form = quoteForm(services=service)
    
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        service = form.services.data
        description = form.more.data
        
        quote_obj = Quotes(name=name, email=email, service=service, description=description)
        try:
            db.session.add(quote_obj)
            db.session.commit()
            flash("Your quote has been received, I will be in touch in a few.", category="info")
            return redirect(url_for('.quote'))
        except Exception as e:
            db.session.rollback()
            flash("Quote not sent, kindly try again.", category="warning")
    return render_template('/mainapp/quote.html', form=form,
                           title=session.get('title'), permission=Permission)

@main_blueprint.route('/projects', methods=['GET', 'POST'])
def projects():
    feedback = Feedback.query.order_by(Feedback.created_at.desc()).all()
    feedback = random.sample(feedback, min(len(feedback), 12))
    return render_template("/mainapp/projects.html", feedback=feedback, permission=Permission)

@main_blueprint.route('/lets-talk', methods=['GET', 'POST'])
def letstalk():
    return render_template("/mainapp/chat.html")

@main_blueprint.route("/resources")
def resources():
    return render_template("/mainapp/resources.html")

@main_blueprint.route("/user/<string:username>/")
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if not user:
        abort(404)
    return render_template("/users/user.html", user=user)

app/templates/include/custom.html
<nav id="nav">
    <ul>
        <li>
            <a href="{{ url_for('blogs.blog_index') }}">Blogs</a>
        </li>
        <li>
            <a href=""><i class="fa-regular fa-bell"></i></a>
        </li>
        <li>
            {% if current_user.is_administrator() %}
            <a href="{{ url_for('users.user', username=current_user.username) }}">
                <img src=" {{current_user.gravatar(size=28) }}" alt="profile picture">
                {{ current_user.username | title }}
            </a>
            {% else %}
                <a href="" title="Anonymous user">
                    {{ current_user.username }}
                </a>
            {% endif %}
        </li>
    </ul>
</nav>

app/templates/include/footer.html
<div class="footer">
    <p>&copy;<span id="year"></span>.<span id="tm">RiriNjaramba</span>&trade;. All rights reserved.</p>
    <p>Made with <i class="fa fa-fire"></i> and <i class="fa fa-heart"></i> by Riri.</p>
    
    <script>
        var year = document.getElementById("year");
        
        const getYear = () =>{
            const date = new Date();

            return date.getFullYear();
        }
        year.innerText = getYear();
    </script>
</div>  

app/templates/include/loader.html
<div class="loader" id="loader">
    <div class="load">
        <div class="spinner">
        </div>
        <h3>Loading...</h3>
    </div>
</div>

app/templates/include/nav.html
<nav class="navigation" id="nav">
    <div class="toggle">
        <button class="button" id="menu-buttton" title="Menu">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <p><a href="{{ url_for('mainapp.index') }}">Riri<span>Njaramba</span></a></p>
    </div>
    <div class="items">
        <ul>
            <li><a href=""></a></li>
            {% if not current_user.is_administrator() %}
                <li id="service"><a href="{{ url_for('mainapp.index') }}#services">Services</a></li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.can(permission.MODERATE_COMMENTS) %}
            <li><a href="{{ url_for('blogs.moderate') }}">Moderate</a></li>
            {% endif %}
            {% if current_user.is_administrator() %}
                <li><a href="{{ url_for('admin.dashboard') }}">Dashboard</a></li>
            {% endif %}
            {% if not current_user.can(permission.MODERATE_COMMENTS) %}
            <li id="quote">
                <a href="{{ url_for('mainapp.quote') }}">Get a Quote</a>
            </li>   
            {% endif %}          
            {%  if current_user.is_authenticated %}
            <li id="dropdown">
                <a class="pro" id="drop-pop">
                    {% if current_user.is_authenticated %}
                        {{ current_user.username | upper }}
                        {% if current_user.is_administrator() %}
                            <img src="{{ url_for('static', filename='/images/riri.jpg') }}" alt="">
                        {% else %}
                            <img src="{{ current_user.gravatar(256) }}" alt="">
                        {% endif %}
                    {% else %}
                        <img src="{{ url_for('static', filename='/images/user.png') }}" alt="">
                        {{ current_user.username | upper }}
                    {% endif %}
                </a>                    
                <ul class="dropdown-menu" id="dropdown-menu">
                    <li class="dropdown-item">
                        <ion-icon name="person-circle-outline"></ion-icon> 
                        <a href="{{ url_for('users.user', username=current_user.username) }}">Profile</a>
                    </li>
                    {% if current_user.is_administrator() %}
                        <li class="dropdown-item">
                            <i class="fa fa-tachometer"></i>
                            <a href="{{ url_for('admin.dashboard') }}">Dashboard</a>
                        </li>
                    {% endif %}                    
                    {% if current_user.can(permission.MODERATE_COMMENTS) %}
                        <li class="dropdown-item">
                            <i class="fa fa-filter"></i>
                            <a href="{{ url_for('blogs.moderate') }}">Moderate</a>
                        </li>
                    {% endif %}
                    {% if current_user.is_authenticated and current_user.can(permission.WRITE_ARTICLE) %}
                        <li class="dropdown-item">
                            <ion-icon name="book-outline"></ion-icon>
                            <a href="{{ url_for('blogs.new_blog') }}">New Blog</a>
                        </li>
                    {% else %}
                        <li class="dropdown-item">
                            <a href=""></a>
                        </li>
                    {% endif %}  
                    <li class="dropdown-item" id="toggle-theme">
                        <i class="fa fa-palette"></i>
                        Change Theme
                    </li>
                    <div class="authent">
                        {% if current_user.is_authenticated %}
                            <li class="dropdown-item">
                                <ion-icon name="log-out-outline"></ion-icon> 
                                <a href="{{ url_for('auth.logout') }}">Logout</a>
                            </li>

                        {% endif %}                          
                    </div>
                </ul>
            </li>
            {% elif current_user.is_anonymous %}
                <li class="login">
                    <a href="{{ url_for('auth.signin') }}">
                        Log in <i class="fa fa-sign-in"></i>
                    </a>
                </li>
            {% endif %}
        </ul>        
    </div>        
</nav>

app/templates/include/sidebar.html
<div class="sidebar" id="sidebar">
    <header>
        <div class="tab">
            <img src="{{ url_for('static', filename='images/riri.jpg')}}" alt="Njaramba">
            <div class="toggle">
                <p><a href="{{ url_for('mainapp.index') }}">Riri<span>Njaramba</span></a></p>
                <button class="close-button" id="menu-button" title="Close">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
        </div>
        <div class="tags" title="Experienced in...">
            <h3 title="Machine Learning.">ML<span>|</span></h3>
            <h3 title="Machine Learning Operations.">MLOPs <span>|</span></h3>
            <h3 title="Web and API development.">Flask <span>|</span></h3>
            <h3>Python <span>|</span></h3> 
            <h3>C++ <span>|</span></h3>
            <h3>CSS <span>|</span></h3>
        </div>
    </header>
    <ul >
        <li id="about-me" data-url="{{ url_for('users.user', username='James') }}">
            <span>My CV
            <ion-icon name="document-outline"></ion-icon>
        </span>
        </li>
        <li>
            <a href="{{ url_for('blogs.blog_index') }}">
                <span>Blogs</span>
                <ion-icon name="book-outline"></ion-icon>
            </a>
            </li>
        <li>
            <a href="{{ url_for('mainapp.projects') }}">
                <span>Projects</span>
                <ion-icon name="laptop-outline"></ion-icon>
            </a>
        </li>
        <li>
            <a href="{{ url_for('mainapp.letstalk') }}">
                <span>Get in touch</span>
                <ion-icon name="chatbubbles-outline"></ion-icon>
            </a>
        </li>
        <li>
            <a href="{{ url_for('mainapp.resources') }}">
                <span>Resources</span>
                <ion-icon name="globe-outline"></ion-icon>
            </a>
        </li>
    </ul>
</div>