app/blogs/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import RecaptchaField
from wtforms import StringField, SubmitField, TextAreaField, HiddenField
from wtforms.validators import Email, DataRequired, Length, Regexp
from flask_pagedown.fields import PageDownField

class BlogPost(FlaskForm):
    title = TextAreaField("Blog title", validators=[DataRequired(message="Jameni, this field can't be empty.")])
    body = TextAreaField("Your blog content", validators=[DataRequired()])
    submit = SubmitField("Publish")

class CommentForm(FlaskForm):
    """Defines the form rendered on blog page for user comments.

    Args:
        Form:Base dorm class. 
    """
    email = StringField("Your Email:", validators=[DataRequired(), Email()])
    name = StringField("Your Name:", validators=[DataRequired(message="Name field can't be empty"), 
                                                 Length(max=30)])
    mawoni = TextAreaField("Your Comment:", validators=[DataRequired(message="Comment field can't be null ffs."), 
                                                       Length(max=500, message="Comment can't be more than 500 characters.")])
    #captcha = RecaptchaField(validators=[DataRequired(message="This is a required field.")])
    submit = SubmitField("comment")


class replyCommentForm(FlaskForm):
    """Defines form for user repplies to other comments.

    Args:
        FlaskForm (Form): Base form class.
    """
    email = StringField("Your email address", validators=[Length(min=10, max=64), DataRequired(),
                                                          Email()])
    name = StringField("Your name", validators=[DataRequired(),
                                                Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, \
                                                             'Usernames must have only letters, numbers, dots or underscores')])
    reply = TextAreaField("Your reply goes here...", validators=[DataRequired(), Length(max=200, message="Replies shouldn't be that long jameni. Eiyyy.")])
    comment_id = HiddenField("Comment ID", validators=[DataRequired()])
    # captcha = RecaptchaField()
    submit = SubmitField("Reply.")
    

app/blogs/__init__.py
def create_app(app, **kwargs):
    from .routes import blog_blueprint
    app.register_blueprint(blog_blueprint)

app/blogs/routes.py
import logging
import random

logging.basicConfig(format=("%(asctime)s: %(name)s:%(levelname)s: %(message)s"))
logging.getLogger().setLevel(logging.DEBUG)

logger = logging.getLogger(__name__)

from flask import Blueprint, render_template, url_for, request, flash, redirect, session, abort, current_app
from flask_login import current_user, login_required
from sqlalchemy import exc, func, text

from app import db
from .models import Posts, Comments, CommentReply, Tag, tags
from .forms import BlogPost, CommentForm, replyCommentForm
from ..auth import permission_required, admin_required
from ..auth.models import Permission, User

blog_blueprint = Blueprint("blogs", __name__, static_folder="/blogs/static",
                           template_folder="/templates/blogs", url_prefix="/bytes")


def sidebar_data():
    recent = Posts.query.order_by(
        Posts.date_created.desc()
    ).limit(5).all()
    
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(
        tags
    ).group_by(Tag).order_by(text('total DESC')).limit(5).all()
    
    return recent, top_tags
    

@blog_blueprint.route('/', methods=['GET', 'POST'])
def blog_index():
    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.date_created.desc())
    blogs = db.paginate(posts, page=page, per_page=4, error_out=False)
    # tag = Tag.query.all()
    # tags = random.sample(tag, 3)
    recent, top_tags = sidebar_data() 
    return render_template("blogs/index.html", posts=posts,
                           top=top_tags,
                           pagination=blogs, recent=recent,
                           permission=Permission)
 
@blog_blueprint.route("/<string:title>", methods=["POST", "GET"])
def blog(title):
    post = Posts.query.filter_by(title=title).first_or_404()
    page = request.args.get('page', 1, type=int)
    comments = Comments.query.filter_by(blog_id=post.post_id).order_by(Comments.date.desc())
    pagination = db.paginate(comments, page=page, per_page=5, error_out=False)
    next_url = url_for('blogs.blog', title=post.title, page=pagination.next_num) if pagination.has_next else None
    prev_url = url_for('blogs.blog', title=post.title, page=pagination.prev_num) if pagination.has_prev else None
    replies = CommentReply.query.order_by(CommentReply.date.desc()).all()
        
    form = CommentForm()
    reply_form = replyCommentForm()
    
    if form.validate_on_submit():
        comment = Comments()
        comment.email = form.email.data
        comment.name = form.name.data
        comment.blog = post
        if current_user.is_authenticated: 
            comment.author = current_user._get_current_object()
        comment.comment = form.mawoni.data
        comment.blog_id = post.post_id
        try:
            db.session.add(comment)
            db.session.commit()
            flash("Your comment was submitted successfully.", category="info")
            return redirect(url_for('blogs.blog', title=title, page=-1))
        except Exception as e:
            db.session.rollback()
            logger.info("Error while adding comment: {}".format(e))
            flash("Error: {}".format(e), category="warning")
    page = request.args.get('page', 1, type=int)     
    if page == -1:
        page = (post.comments.count() -1) / current_app.config['COMMENTS_PER_PAGE'] + 1
    pagination  = post.comments.order_by(Comments.date.asc()).paginate(
        page=page, per_page=current_app.config['COMMENTS_PER_PAGE'], error_out=False
        )
    comments = pagination.items
            
    return render_template("blogs/blog.html", blog=post, 
                           form=form, reply=reply_form, replies=replies, 
                           comments=comments, pagionation=pagination, enumerate=enumerate,
                           comment=pagination.items, next=next_url, prev=prev_url, permission=Permission)

@blog_blueprint.route("/comment/<int:comment_id>/reply/", methods=['POST', 'GET'])
def comment_reply(comment_id):
    comment = Comments.query.filter_by(id=comment_id).first_or_404()
    
    reply = CommentReply()
    reply_form = replyCommentForm()
    if request.method == 'POST' and reply_form.validate_on_submit():
        if current_user.is_authenticated:
            email = current_user.email 
            name = current_user.username
        else:
            email = reply_form.email.data
            name = reply_form.name.data    
        
        reply.email = email
        reply.name = name
        reply.reply = reply_form.reply.data
        reply.comment_id = comment.id
        try:
            db.session.add(reply)
            db.session.commit()
            flash("Reply sent successfully", category="info")
            return redirect(url_for('blogs.blog', title=comment.blog.title))
        except Exception as e:
            db.session.rollback()
            flash(f"Reply not sent: {e}", category="warning")
            logger.error("User reply could not be sent: {}".format(e))
    return redirect(url_for('blogs.blog', title=comment.blog.title))

@blog_blueprint.route("/tag/<string:tag_name>")
def blog_by_tag(tag_name):
    tag = Tag.query.filter_by(name=tag_name).first_or_404()
    posts = tag.Blogs.order_by(Posts.date_created.desc()).all()
    
    recent, top_tags = sidebar_data()
    
    return render_template("blogs/tag.html", posts=posts, tag=tag_name,
                           recent=recent, top=top_tags, permission=Permission)

@blog_blueprint.route('/post/<int:id>')
def post(id):
    post = Posts.query.get_or_404(id)
    return redirect(url_for('blogs.blog', title=post.title))

@blog_blueprint.route('/new/', methods=['POST', 'GET'])
@login_required
@permission_required(Permission.WRITE_ARTICLE)
def new_blog():
    user = User.query.get_or_404(current_user.id)
    blogs = user.posts.order_by(Posts.date_created.desc()).limit(5).all()
    # page = request.args.get('page')
    # pagination = db.paginate(blogs, page=page, per_page=3, error_out=False)
    form = BlogPost()
    if current_user.can(Permission.WRITE_ARTICLE) and form.validate_on_submit():
        post = Posts(post_author=current_user.username, title=form.title.data, 
                     post=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.blog', title=post.title))
    return render_template("blogs/new_blog.html", form=form, permission=Permission, 
                           blogs=blogs, user=user)

@blog_blueprint.route("/edit/<int:blog_id>/", methods=['GET', 'POST'])
@login_required
@permission_required(Permission.WRITE_ARTICLE)
def edit_blog(blog_id):
    blog = Posts.query.filter_by(post_id=blog_id).first()
    user = User.query.filter_by(username=blog.author.username).first_or_404()
    if current_user != blog.post_author \
        and not current_user.can(Permission.ADMINISTER):
        abort(404)
    posts = user.posts.order_by(Posts.date_created.desc()).limit(5).all()
    form = BlogPost()
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.post = form.body.data
        try:
            db.session.add(blog)
            db.session.commit()
            flash("BLog post has been updated, your're reading the latest version.", category="info")
            return redirect(url_for('.blog', title=blog.title))
        except exc.IntegrityError as e:
            db.session.rollback()
            logger.error("Error when updating plog post: {}".format(e))
            flash("For some unforeseen reason, blog post could not be updated", category="warning")
    form.title.data = blog.title
    form.body.data = blog.post
    return render_template("blogs/edit.html", form=form, posts=posts,
                            blog=blog, user=blog.author, permission=Permission)

@blog_blueprint.route('/remove/<int:blog_id>', methods=['DELETE', 'GET'])
@login_required
@permission_required(Permission.WRITE_ARTICLE)
def delete(blog_id):
    blog = Posts.query.filter_by(post_id=blog_id).first_or_404()
    try:
        db.session.delete(blog)
        db.session.commit()
        flash("Your blog piost has been deleted successfully.", category="info")
        return redirect(url_for(".blog_index", page=1))
    except Exception as e:
        db.session.rollback()
        flash("Your blog was not deleted, try later.", category="warning")
        return redirect(url_for('.blog_index', page=1))
        
@blog_blueprint.route("/hide/<int:blog_id>/", methods=['POST', 'GET'])
@login_required
@permission_required(Permission.WRITE_ARTICLE)
def hide(blog_id):
    blog = Posts.query.filter_by(post_id=blog_id).first_or_404()
    try:
        if blog.disabled:
            blog.disabled = False
        elif not blog.disabled:
            blog.disabled = True
        
        db.session.add(blog)
        db.session.commit()
        flash("Blog's visibility status updated successfully", category="info")
        return redirect(url_for('.blog_index', page=1))
    except Exception as e:
        db.session.rollback()
        flash("Blog visibility status not changed, try later", category="warning")
        return redirect(url_for('.blog_index', page=1))
        

@blog_blueprint.route("/moderate-comments/")
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comments.query.order_by(Comments.date.desc()).paginate(
        page=page, per_page=current_app.config['COMMENTS_PER_PAGE'], error_out=False
    )
    comments = pagination.items
    
    return render_template("blogs/moderate.html", pagination=pagination,
                           comments=comments, page=page, permission=Permission)
    
@blog_blueprint.route("/comment/enable/<int:id>")
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comments.query.get_or_404(id)

app/users/routes.py
from flask import (Blueprint, render_template , url_for, 
                   abort, send_file, request, redirect, flash)
from flask_login import current_user

from app import db
from .forms import fileForm, aboutForm, updateBio
from ..auth.models import Permission, User, Role
from ..blogs.models import Posts, Comments

user_blueprint = Blueprint("users", __name__,
                           static_folder="static/users", template_folder="template/users",
                           url_prefix="/user/")

@user_blueprint.route('/@<string:username>/', methods=['POST', 'GET'])
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if not user:
        abort(404)
    posts = user.posts.order_by(Posts.date_created.desc()).all()
    comments = user.comments.order_by(Comments.date.desc()).all()
    form = fileForm()
    about = aboutForm()
    bio = updateBio()
    if about.validate_on_submit():
        user.about = about.about.data
        try:
            db.session.add(user)
            db.session.commit()
            flash("Your professional summary was successfully updated", category="info")
            return redirect(url_for('.user', username=user.username))
        except Exception as e:
            db.session.rollback()
            flash(f"Oppsie!, about not updated: {e}", category="warning")
            
    if bio.validate_on_submit():
        user.display_name = bio.name.data
        user.location = bio.location.data
        user.interests = bio.interests.data
        user.bio = bio.bio.data
        try:
            db.session.add(user)
            db.session.commit()
            flash("Profile details changed succesfully.", category="info")
            return redirect(url_for('.user', username=user.username))
        except Exception as e:
            db.session.rollback()
            flash("Profile details not updated, try again later.", category="warning")
        
    if user.about:
        about.about.data = user.about
        bio.bio.data = user.bio
        bio.location.data = user.location
        bio.name.data = user.display_name
        bio.interests.data = user.interests
        
    return render_template("/users/user.html", user=user, about=about, bio=bio,
                           posts=posts, comments=comments, form=form, permission=Permission)

@user_blueprint.route('/upload-cv', methods=['GET','POST'])
def upload_file():
    if 'file' not in request.files:
        flash("No file part", category="warning")
    
    file = request.files['file']
    
    if file.filename == '':
        flash("No file selected", category="warning")
    
    file.save("app/static/uploads/" + file.filename)
    flash("File uploaded successfully", category="info")
    
    return redirect(url_for('.user', username=current_user.username))

@user_blueprint.route('/')
def download_cv():
    file = "/home/riri/Desktop/RiriNjaramba/app/static/images/riri.jpg"
    
    return send_file(file, as_attachment=True)

app/templates/blogs/blog.html
{% extends 'base.html' %}

{% block title %} Riri Njaramba -  {{ blog.title }}{% endblock %}

{% block content %}
{% include 'include/nav.html' %}
{% include 'include/sidebar.html' %}
<div class="blogs-page">
    <div class="items">
        <div class="blog">
            <div class="overview">
                <p>Authored by: 
                    <span>
                        <a href="{{ url_for('users.user', username=blog.post_author)}}">

                            {{ blog.post_author }}
                        </a>
                    </span> </p>
                <p>On: <span>{{ moment(blog.date_created).format('LL')}}</span></p>
                {% if blog.updated %}
                    <p>Last update: <span>{{ moment(blog.date_updated).format('LLL') }}</span> 
                        [{{ moment(blog.date_updated).fromNow() }}]</p>
                {% endif %}   
                {% if current_user == blog.author %}
                    <a href="{{ url_for('.edit_blog', title=blog.title)}}">Edit post.</a>
                {% elif current_user.is_administrator() %}
                    <a href="{{ url_for('.edit_blog', title=blog.title)}}">Edit [Admin].</a>
                {% endif %}
                <a href="{{ url_for('.blog', title=blog.title) }}#comments">
                    <span class="label label-primary">
                    {{ blog.comments.count() }} Comments
                    </span>
                </a>
                <button class="submit" onclick="goBack()">Go Back</button>
            </div>
            <div class="blog-content">
                <div class="header">
                    {% if blog.title_html %}
                        <h2>{{ blog.post_html | safe }}</h2>
                    {% else %}
                        <h2>{{ blog.title }} </h2>
                    {% endif %}
                </div>                
                {% if blog.post_html %}
                    {{ blog.post_html | safe }}
                {% else %}
                   {{ blog.post }}
                {% endif %} 
            </div>
        </div>
        <div class="comments">
            <h3 id="comments">Blog comments.</h3>
            {% if not comments %}
                <div class="go-comment">
                    <p>
                        This post is yet to receive comments. Be the first one to leave a comment. 
                        <i class="fa-solid fa-hand-point-down"></i>
                    </p>
                </div>
            {% endif %}
            {% for comment in comments %}
                {% if not comment.disabled %}
                    <div class="blog-comment" id="{{ comment.id }}">
                        <div class="author">
                            <div class="name">
                                <p>
                                    <span>{{  moment(comment.date).fromNow() }}</span>
                                    {% if comment.author.id == current_user.id %}
                                        you
                                    {% else %}    
                                        <span id="{{ comment.name }}">
                                            {% if comment.author.display_name %}
                                                {{ (comment.author.display_name).split()[0] }},
                                            {% elif comment.author.username %}
                                                {{ comment.author.username | title }},
                                            {% else %}
                                                {{ comment.name }},
                                            {% endif %}                                       
                                        </span>
                                     {% endif %}
                                </p>
                            </div>                    
                            <div class="date">
                                <p>said:</p>
                            </div>                  
                        </div>
                        <div class="authored">
                            <div class="reply">
                                {{ comment.comment }}
                            </div>
                        </div>   
                        <div class="discussion reply">
                            <p class="open-reply" title="Reply to {{ comment.name }}.">Open discussion.</p>
                        </div>
                        <div class="discussion">
                            <div class="reply-comment">
                                <div class="replies">
                                    {% if replies %}
                                        <p>Comment replies</p>
                                        {% for i, reply in enumerate(replies, start=1) %}
                                            {% if reply.comment_id == comment.id %}
                                                <div class="reply" aria-label="close">
                                                    <!-- <p></p> -->
                                                    
                                                    <p><span class="rep-id" id="rep-id">#{{ i }}</span> 
                                                        On <span>{{ moment(reply.date).format('LL') }}</span>
                                                        <span> {{ reply.name }}</span>said: </p> 
                                                    <p>{{ reply.reply }}</p>                          
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </div>                        
                                {% if current_user.is_anonymous %}
                                    <div class="sign">
                                        <p id="sign" onclick="goSign()" title="Sign in so you can reply to {{ comment.name }}" 
                                        data-url="{{ url_for('auth.signin') }}">Sign in to reply.</p>
                                    </div>
                                    <p class="mid">or</p>
                                {% endif %}
                                <form action="{{ url_for('blogs.comment_reply', comment_id=comment.id) }}" method="post">
                                    {{ reply.hidden_tag() }}
                                    {% for field in reply %}
                                        {% if field.type == 'HiddenField' %}
                                            {{ field(value=comment.id) }}
                                        {% elif field.type == 'StringField' %}
                                            {% if current_user.is_anonymous %}
                                                {% if field.name == 'email' %}
                                                    <div class="input-reply">
                                                        {{ field.label }}
                                                        <small><i class="fa fa-info-circle"></i> Your email won't be shared.</small>
                                                        {{ field(class_='reply-input') }}
                                                    </div>
                                                {% else %}
                                                    <div class="input-reply">
                                                        {{ field.label }}
                                                        <small><i class="fa fa-info-circle"></i> This will be shared.</small>
                                                        {{ field(class_='reply-input') }}                                                
                                                    </div>
                                                {% endif %}
                                            {% endif %}  
                                            {% if field.errors %}
                                                {% for e in field.erros %}
                                                    <p class="help-block">{{e}}</p>
                                                {% endfor %}
                                            {% endif %}                              
                                        {% elif field.type == 'TextAreaField' %}
                                            <div class="actual">
                                                {{ field(class_='text-area', placeholder=field.label.text) }}
                                            </div>
                                        {% else %}
                                            {% if current_user.is_authenticated %}
                                                <div class="" title="Replying to {{ comment.name | truncate(15) | title }}  as {{ current_user.username | title }}">
                                                    {{ field(class_='reply-btn') }}
                                                </div>
                                            {% else %}
                                                <div class="">
                                                    {{ field(class_='reply-btn', title=url_for('.comment_reply', comment_id=comment.id)) }}
                                                </div>
                                            {% endif %}
                                        {% endif %}                                    
                                    {% endfor %}
                                </form>                      
                            </div>
                        </div>             
                    </div>
                {% else %}
                    <div class="blog-comment">
                        <div class="author">
                            <div class="name">
                                <p>
                                    <span>{{  moment(comment.date).fromNow() }},</span>
                                    <span>{{ comment.author.display_name }}</span>
                                </p>
                            </div>                    
                            <div class="date">
                                <p>said:</p>
                            </div>                   
                        </div>
                        <div class="authored">
                            <div class="reply" style="text-decoration: line-through;">
                                {{ comment.comment | truncate(20) }}
                            </div>
                        </div>  
                        <small style="color: brown;">
                            <i class="fa fa-warning"></i> 
                            This comment is disabled by moderators. 
                            <i class="fa fa-warning"></i>
                            <a href="" style="text-decoration: none; padding-left: 1rem;">Learn more <i class="fa fa-info-circle"></i></a>
                        </small>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="pagination">
                {% if prev %}
                    <a href="{{ prev }}">Prev <i class="far fa-caret"></i></a>
                {% endif %}                 
                {% if next %}
                    <a href="{{ next }}">Next</a>
                {% endif %}
            </div>
        </div>
        <div class="comment">
            <div class="comment-form">
                <h3>Want to leave a comment?.</h3>
                <form action="{{ url_for('.blog', title=blog.title)}}" method="post">
                    {% for field in form %}
                    {% if field.type == 'StringField' %}
                        <div class="field">
                            {{ field.label(class_='label') }}
                            {% if field.name == 'email' %}
                                {{ field(class_='input-area', autofill='none', title="Don't worry, your email won't be displayed." ) }}
                            {% else %}
                                {{ field(class_='input-area', autofill='none') }}
                            {% endif %}
                            {% if field.errors %}
                                {% for e in field.errors %}
                                <p class="help-block">{{ e }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% elif field.type == 'TextAreaField' %}
                        <div class="text">
                            {{ field.label(class_='label') }}
                            {{ field(class_='text-area') }}
                        </div>
                    {% elif field.type == 'RecaptchaField' %}
                        <div class="captcha">
                            {{ field(class_='captcha') }}
                        </div>
                    {% else %}
                        {{ field (class_='submit') }}
                    {% endif %}
                    {% endfor %}
                </form>
            </div>              
        </div>
    </div>
</div>
{% block js %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
    {{ moment.include_moment() }}

    <script type="text/javascript">
        function goBack(){
            window.history.back()
        }

        const sign = document.getElementById('sign');

        sign.addEventListener('click', function(){
            var url = sign.dataset.url;
            
            setTimeout(function(){
                window.location.href = url;
            }, 500);
        });
    </script>
{% endblock js %}
{% endblock %}